---
#
# Litmus tests
#
kind: pipeline
type: docker
name: matrix-1
workspace:
  base: /var/www/owncloud

services:
  - name: server
    image: owncloudci/php:7.4
    environment:
      APACHE_WEBROOT: /var/www/owncloud/server
      APACHE_LOGGING_PATH: /dev/null
    commands:
      - /usr/local/bin/apachectl -e debug -D FOREGROUND

  - name: mysql
    image: mysql
    environment:
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud
      MYSQL_ROOT_PASSWORD: owncloud
    command:
      - --default-authentication-plugin=mysql_native_password

steps:
  - name: install-core
    image: owncloudci/core
    settings:
      version: daily-master
      core_path: /var/www/owncloud/server
      db_type: mysql
      db_name: owncloud
      db_host: mysql
      db_username: owncloud
      db_password: owncloud

  - name: wait-for-server
    image: owncloudci/wait-for:latest
    commands:
      - wait-for -it server:80 -t 600

  - name: setup-server
    image: owncloudci/php:7.4
    commands:
      - cd /var/www/owncloud/server
      - php occ config:system:set trusted_domains 1 --value=server

  - name: fix-permissions
    image: owncloudci/php:7.4
    commands:
      - chown -R www-data /var/www/owncloud/server

  - name: owncloud-log
    image: owncloud/ubuntu:20.04
    detach: true
    commands:
      - tail -f /var/www/owncloud/server/data/owncloud.log

  - name: litmus-old-api
    image: owncloudci/litmus
    environment:
      LITMUS_PASSWORD: admin
      LITMUS_USERNAME: admin
      LITMUS_URL: http://server:80/remote.php/webdav
    commands:
      - litmus-wrapper

  - name: litmus-new-api
    image: owncloudci/litmus
    environment:
      LITMUS_PASSWORD: admin
      LITMUS_USERNAME: admin
      LITMUS_URL: http://server:80/remote.php/dav/files/admin
    commands:
      - litmus-wrapper

trigger:
  ref:
    - refs/tags/**
    - refs/heads/master
    - refs/pull/**

#
# Rocket-caht Notification
#
---
kind: pipeline
type: docker
name: chat-notifications
clone:
  disable: true

steps:
  - name: notify-rocketchat
    image: plugins/slack:1
    settings:
      webhook:
        from_secret: rocketchat_chat_webhook
      channel: builds

depends_on:
  - matrix-1

trigger:
  ref:
    - refs/tags/**
    - refs/heads/master
  status:
    - success
    - failure
