workspace:
  base: /var/www
  path:

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  owncloud-server:
    image: owncloudci/core
    pull: true
    detach: true
    settings:
      version: ${SERVER_VERSION}
      core_path: /var/www
      db_type: mysql
      db_name: owncloud
      db_host: mysql
      db_username: owncloud
      db_password: owncloud

  owncloud-waiting:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 300 owncloud-server:8080

  litmus-oldapi:
    image: owncloud/litmus:${LITMUS_VERSION}
    pull: true
    environment:
      - LITMUS_URL=http://owncloud-server:8080/remote.php/webdav
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    commands:
      - litmus-wrapper

  litmus-newapi:
    image: owncloud/litmus:${LITMUS_VERSION}
    pull: true
    environment:
      - LITMUS_URL=http://owncloud-server:8080/remote.php/dav/files/admin
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    commands:
      - litmus-wrapper

  notify-rocketchat:
    image: plugins/slack:1
    pull: true
    secrets: [slack_webhook]
    channel: litmus
    template: >
      *{{build.status}}* <{{build.link}}|{{repo.owner}}/{{repo.name}}#{{truncate build.commit 8}}> basic:litmus:${SERVER_VERSION}:general
    when:
      local: false
      status: [changed, failure]

services:
  mysql:
    image: library/mariadb:10.3
    pull: true
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud

  redis:
    image: library/redis:4.0
    pull: true

matrix:
  include:
    - LITMUS_VERSION: latest
      SERVER_VERSION: daily-master
