workspace:
  base: /var/www
  path:

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  owncloud-download:
    image: plugins/download:1
    pull: true
    source: https://download.owncloud.com/server/daily/owncloud-${SERVER_VERSION}.tar.bz2

  owncloud-unpack:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - tar -jxf owncloud-${SERVER_VERSION}.tar.bz2 -C /var/www

  owncloud-server:
    image: owncloud/base:bionic
    pull: true
    detach: true
    environment:
      - OWNCLOUD_DOMAIN=owncloud-server
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mysql
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin

  owncloud-waiting:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - wait-for-it -t 300 owncloud-server:8080

  litmus-oldapi:
    image: owncloud/litmus:${LITMUS_VERSION}
    pull: true
    environment:
      - LITMUS_URL=http://owncloud-server:8080/remote.php/webdav
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    commands:
      - litmus-wrapper

  litmus-newapi:
    image: owncloud/litmus:${LITMUS_VERSION}
    pull: true
    environment:
      - LITMUS_URL=http://owncloud-server:8080/remote.php/dav/files/admin
      - LITMUS_USERNAME=admin
      - LITMUS_PASSWORD=admin
    commands:
      - litmus-wrapper

  notify-rocketchat:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: litmus
    template: >
      *{{build.status}}* <{{build.link}}|{{repo.owner}}/{{repo.name}}#{{truncate build.commit 8}}> basic:litmus:${SERVER_VERSION}:general
    when:
      local: false
      status: [ changed, failure ]

services:
  mysql:
    image: library/mariadb:10.3
    pull: true
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud

  redis:
    image: library/redis:4.0
    pull: true

matrix:
  include:
    - LITMUS_VERSION: latest
      SERVER_VERSION: daily-master
